name = "Bigspring"
license = "MIT"
licenselink = "https://github.com/themefisher/bigspring/blob/master/LICENSE"
description = "A hugo theme by themefisher"
homepage = "https://gethugothemes.com/products/bigspring-hugo/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"